### PR TITLE
More about Features

### PR DESCRIPTION
**Pull request by Smada95**
I thought this should be clarified

### CODE REVIEW

**Comment by Strevia** [comment]
Ooh I like that, I hadn't thought of it.
Also, do I need to add a spellchecker

**Comment by Smada-nailuj** [comment]
Listen a spell checker would be very useful for me

**Comment by Strevia** [comment]
I don't seem to be able to make a pull into your branch but it should be "its height"

**Comment by Smada-nailuj** [comment]
Weird, I'm on mobile though so haven't figured out how to do anything besides comment

**Comment by Smada95** [comment]
Why was this marked as amendment. Are you asking for it to be rewritten to be an amendment to rule 10?

**Comment by Strevia** [comment]
My bad just looked at the title and remembering the contents thought it was an ammendment

**Pull request merged**
