### PR TITLE
Ammendment to rule 4 and adding rule 8

### PR DESCRIPTION
**Pull request by Strevia**
Amendment to rule 4, which changes language from "building" blocks to "placing" blocks. Also specified the cost of blocks. Adding rule 8. This says that you can place a block on your tower at a cost of the current height of your tower in blocks. While I know these are two separate rule changes, I think proposing them separately would put the game in a weird limbo if only one got accepted. Also, this gets me less points anyway

### CODE REVIEW

**Comment by Strevia** [comment]
@Smada-nailuj

**Comment by Smada-nailuj** [comment]
This would get you how many points?

**Comment by Strevia** [comment]
The rule says
> Anytime a player proposes a change to rules.md and it passes, they get 1 point.

Since I only proposed the change once I think only 1 point.

**Comment by Smada-nailuj** [comment]
So you spend points to build and place blocks?

**Comment by Smada-nailuj** [comment]
Could you add a formula for how to cost increases to appendix_F?

**Comment by Strevia** [comment]
> So you spend points to build and place blocks?

Yes.

> Could you add a formula for how to cost increases to appendix_F?

I have some thoughts on appendix F, see my comment on #25

**Comment by Smada-nailuj** [comment]
> 8. Once a block has been built, a player may add to their tower at a point cost equal to the current height of the player's tower in number of blocks.

I think it should be reworded to 

> 8. Once a block has been built, a player may add [it] to their tower at a point cost equal to the current height of the player's tower in number of blocks. 

and add entry in appendix_F.md to state and explain the cost.

**Comment by Strevia** [comment]
@Smada-nailuj all good? Also fixed a potentially devastating consequence of your formula I didn't notice

**Comment by Smada-nailuj** [comment]
What does adding \ to  floor(log[base2](m))+1 do?

**Comment by Strevia** [comment]
> What does adding \ to floor(log[base2](m))+1 do?
> 
> `floor(log[base2]\(m))+1`

Markdown seems to interpret the formula without the backslash as a link (if you look at appendix f currently, it looks like you forgot m). The backslash fixes the formatting

**Comment by Smada-nailuj** [comment]
image
Not for me

**Comment by Strevia** [comment]
The way it is in the quote was how it appeared for me in the actual file

**Comment by Strevia** [comment]
Also @Smada-nailuj just looked at your comment and you have a few hidden backslashes that don't show up when it's displayed

**Comment by Smada-nailuj** [comment]
I looked at the actual file and yeah thats my bad

**Comment by Strevia** [comment]
Any other objections?

**Comment by Strevia** [comment]
@Smada-nailuj

**Pull request merged**
