### PR TITLE
Tower Feature: Apartment

### PR DESCRIPTION
**Pull request by Strevia**
Willing to negotiate numbers in price/effect (might be OP).

### CODE REVIEW

**Comment by Smada-nailuj** [comment]
Commenting so I can see this on mobile

**Comment by Smada-nailuj** [comment]
Also I think it would be cooler if there were a line feature that you could send your people to work at instead of them mining in the apartment

**Comment by Strevia** [comment]
Yes, it would come with people. So you think that a mining feature should be separate?

**Comment by Smada95** [comment]
> Yes, it would come with people. So you think that a mining feature should be separate?

Yes.

**Comment by Smada95** [comment]
When does the day roll over? Also I don’t think they should Pay taxes/rent without some kind of town hall/central bureaucracy tower feature

**Comment by Strevia** [comment]
> When does the day roll over? Also I don’t think they should Pay taxes/rent without some kind of town hall/central bureaucracy tower feature

See #75 for the day mechanic. In regards to town hall/bureaucracy, they're giving their taxes directly to the owner of the tower.

**Comment by Smada95** [comment]
> In regards to town hall/bureaucracy, they're giving their taxes directly to the owner of the tower.

I'm saying that taxes should be a separate tower feature like #76

**Comment by Strevia** [comment]
I think points being solely tied to rule proposals like they are now is severely limiting our ability to progress the game. I'd like to add another way to get points that we can start using ASAP.

**Comment by Strevia** [comment]
@Smada95 made some changes

**Comment by Smada95** [comment]
I'll approve this

**Pull request merged**
