### PR TITLE
Stimulus cheque

### PR DESCRIPTION
**Pull request by Smada95**
I didn't know this would effect my pull requests

This is a clone of #51

### CODE REVIEW

**Comment by Strevia** [comment]
If it doesn't apply retroactively I think it's too little too late

**Comment by Smada95** [comment]
Well I thought rules couldn't apply retroactively, I might be confusing myself though.

**Comment by Smada95** [comment]
I was confused about rules being allowed to take effect retroactively

**Comment by Strevia** [comment]
I think what we mean by rules not applying retroactively is that you can't be punished for something you did before it was disallowed by the rules. I.e. if someone had built more features than their in height before the rule passed we couldn't just force them to get rid of one

**Comment by Strevia** [comment]
If you add a misspelled word to the dictionary it kinda defeats the purpose of the spellcheck

**Comment by Smada95** [comment]
How are they misspelled?

**Comment by Strevia** [comment]
Retroactivly is spelled retroactively

**Comment by Strevia** [comment]
Could you remove the misspelled retroactivly from expect.txt

**Comment by Smada95** [comment]
I believe I have removed the incorrect words

**Comment by Strevia** [comment]
So if this gets passed, everyone including inactive players get 3 points each?

**Comment by Smada95** [comment]
Yes, and then 3 more points when rule 20 is passed etc.

**Pull request merged**
