### PR TITLE
Rule amendment

### PR DESCRIPTION
**Pull request by Smada-nailuj**
Makes a change to rule 5 to define the size of the blocks being placed.

### CODE REVIEW

**Comment by Strevia** [comment]
Will this rule change go with the currently in the works rule 7 regarding winning? If so, sounds good to me

**Comment by Smada-nailuj** [comment]
Please clarify your question

**Comment by Strevia** [comment]
This rule states that blocks are 1 kilo-cubit, and the currently in the works "one small step" rule says that " It takes 84,000,000 cubit-sized blocks to reach the Moon." Are kilo-cubits related to these 84,000,000 cubits?

**Comment by Smada-nailuj** [comment]
They are both cubits, I suppose I should clarify the rule to be that the cubes are 1 Kilo-cubit³. I see no other relation between this amendment to rule 5 and the proposed rule 7 aside from using the same unit of measurement.

**Pull request merged**
