### PR TITLE
Rule 8.md

### PR DESCRIPTION
**Pull request by Smada-nailuj**
Proposes a mechanic based on tower height

### CODE REVIEW

**Comment by Strevia** [comment]
Are you planning on making apendex_F.md? Would a change to it have to be approved unanimously? What happened to appendices A-E?

**Comment by Smada-nailuj** [comment]
> Are you planning on making apendex_F.md?
Yes; appendix_F.md is for formulas. 

>  Would a change to it have to be approved unanimously?
Thats a question for Issues

> What happened to appendices A-E?
I've never heard of appendices A-E.

**Comment by Smada-nailuj** [comment]
also @Strevia If you look at the time stamps, appendix_F.md was created before you commented that question so please in the future check before asking.

**Comment by Strevia** [comment]
> also @Strevia If you look at the time stamps, appendix_F.md was created before you commented that question so please in the future check before asking.

They both say 10:14 for me, it may have been created while I was typing that reply. I did do it pretty quickly, in the future I will wait a bit before that kind of comment, my apologies.

**Comment by Strevia** [comment]
Also "multipleier" is multiplier and "apendex" is appendix, unless you don't want it to apply to this rule

**Comment by Strevia** [comment]
To resolve the merge conflict, you can rename rules.md to rules/rules.md. Then you should be able to resolve it from the website GUI.

**Comment by Smada-nailuj** [comment]
Well?

**Pull request merged**
