### PR TITLE
Introducing Heroes!

### PR DESCRIPTION
**Pull request by Smada95**
11. Heroes have four main stats between 1-5, BDY (Body) MAG (Magic) DEF (Defense) SPD (Speed). When a new hero object is created it has 15 XP to allocate among those four stats, the first and second rank take 1 XP, the third and fourth rank take 2 XP, and the fifth rank takes 3 XP to purchase. Heroes Names can be any combination between Three and Twenty alphanumeric characters. Heroes start at level 1 and with 10 HP plus its Body.

### CODE REVIEW

**Comment by Strevia** [comment]
Are you just trying to see how many typos you can get past me?

**Comment by Smada-nailuj** [comment]
would you mind making a pull to fix all those typos?

**Comment by Strevia** [comment]
theird fith combonation

**Comment by Strevia** [comment]
Not sure you got "combination"
Also, I'm very confused about what exactly this rule is

**Comment by Smada-nailuj** [comment]
It's a ground work rule

**Comment by Strevia** [comment]
Honestly for a groundwork rule it seems a bit too confusing/complicated...
Maybe if it related back to the main mechanism of the game, towers?

**Comment by Smada-nailuj** [comment]
I do have plans for how hero's can interact with towers but the rule was already getting long.

**Comment by Smada-nailuj** [comment]
I also object that the main mechanism of the game is tower. The main mechanism is proposing rules.

**Comment by Strevia** [comment]
OK where are heroes stored exactly? The rule says a new "hero object"

**Comment by Smada-nailuj** [comment]
With the player that created it

**Comment by Smada-nailuj** [comment]
With the introduction of apartments, hero's would probably be created by promoting a person to an adventurer

**Comment by Smada95** [comment]
@Strevia pls add these to the spell check

**Pull request closed without merging**
