### PR TITLE
Add a rule which allows players to create custom features

### PR DESCRIPTION
**Pull request by Strevia**
Add a new rule which allows players to create custom features which can be added to the towers. These features will be stored in appendix_T.md as part of the rules subfolder and so need to be approved.

10. Players may create additional features which they can add to their towers. When creating a feature, a player needs to specify: a name, a cost in blocks and/or points, and a unique effect. These features will be stored in appendix_T.md.

### CODE REVIEW

**Comment by Strevia** [comment]
@Smada-nailuj

**Comment by Smada-nailuj** [comment]
Could I get some examples of the format of a feature and an example of effects that could arise from these unique features?

**Comment by Strevia** [comment]
@Smada-nailuj 
Examples:
Name: Laser Cannon
Cost: 10 points
Effect: Single-use, lets you destroy one block from another player's tower

Name: Apartment
Cost: 5 blocks
Effect: Can house 2 people. Each person can make 100 cubits of block a day.

Name: Upgrader
Cost: 5 x the cost of the upgraded feature
Effect: Doubles the effects of whatever feature it is used to upgrade

These are just examples, numbers are probably bad

**Comment by Strevia** [comment]
I should specify, my intent is that once a tower feature is in appendix T, anyone can create that tower feature if they have the specified cost

**Comment by Smada-nailuj** [comment]
Good clarification, I had assumed that was the case

**Pull request merged**
