### PR TITLE
Rule 7: A way to win

### PR DESCRIPTION
**Pull request by Strevia**
One small step for nomic

### CODE REVIEW

**Comment by Smada-nailuj** [comment]
This needs to include some definitions of how many blocks away the moon is, etc.

**Comment by Smada-nailuj** [comment]
probably

**Comment by Strevia** [comment]
Added a number, that can be reduced if it's too high

**Comment by Strevia** [comment]
@Smada-nailuj what do you think of the change

**Comment by Smada-nailuj** [comment]
I just saw across the spider verse and it was amazing

**Pull request merged**
