### PR TITLE
Add Formula for proposed rule 8 to appendix_F.md

### PR DESCRIPTION
**Pull request by Smada-nailuj**
Adds a formula for rule 8, #24

### CODE REVIEW

**Comment by Strevia** [comment]
I think before we start making new files, we need to clarify in the rules how these files can be changed. The rules say 
> All players must agree to any changes to these rules.

Currently I take that as just changed to rules.md. I've made changes to the README and the github issue templates without any approval since that wasn't rules.md. Perhaps the system needs restructuring, maybe a full rules folder where anything within it needs player approval?

**Comment by Strevia** [comment]
Also I see at least 3 typos:
definied -> defined
players -> player's
succsesfully -> successfully
(the first and last have red squiggly lines on my computer)

**Comment by Smada-nailuj** [comment]
I'm not sure how to modify this pull request to change the end location of the file

**Comment by Strevia** [comment]
> I'm not sure how to modify this pull request to change the end location of the file

You should just be able to rename the file to rules/appendix_F.md.

**Comment by Smada-nailuj** [comment]
So what other objections do you have to this?

**Comment by Strevia** [comment]
Depending on which, if either, rule 8 is merged first, this might need to be changed. It should probably be blank to start and add the rule 8 change(s) to our respective pull requests

**Comment by Smada-nailuj** [comment]
Conflicts have been resolved

**Comment by Smada-nailuj** [comment]
In the future I'll add things like this to the original pull request I'm still getting used to using Github.

**Pull request merged**
