### PR TITLE
Tower Feature: Tower Hall

### PR DESCRIPTION
**Pull request by Smada95**
Unlocks Taxation Without Representation.

### CODE REVIEW

**Comment by Strevia** [comment]
I think this is much too expensive. I think points being solely tied to rule proposals like they are now is severely limiting our ability to progress the game. I'd like to add another way to get points that we can start using ASAP.

**Comment by Smada95** [comment]
What about changing it to be 2 points and making apartments cost more the more you have?

**Comment by Strevia** [comment]
> What about changing it to be 2 points and making apartments cost more the more you have?

I made apartments cost more the more you have. I think it's also worth noting tower height also increases in cost the more you have.

**Comment by Strevia** [comment]
Personally I don't see any reason for this to cost points. Maybe make it free (but still cost height of course)

**Pull request merged**
